### ISSUE TITLE
The target value in the logs is wrong

### ISSUE THREAD

**Issue by outdoteth** [fmfn/BayesianOptimization#298] opened 2021-11-26 21:05 UTC
The 18th trial shows a target of -1.826e+0. But at the bottom you can see that the actual target value is  -182571.40432067157. It's wrong by several orders of magnitude.

![screenshot_952](https://user-images.githubusercontent.com/37438950/143647226-8e0e2325-c873-4b8d-ade4-445637a29d96.png)

**Comment by bwheelz36** [comment] 2021-12-06 22:01
What exactly are we looking at here? is this the value in the json file created by bayes_opt.logger.JSONLogger?

I've never had a problem with this - could you check the log file directly? my first guess is that this is just an issue in the way the values are being displayed...

**Comment by eschibli** [comment] 2021-12-10 00:13
The issue is that the column is truncated - it should read `-1.826E+05`, but the five is cut off.

I'm not sure what causes this because I'm not an expert in this package, but I've seen this before and I believe everything except the printing is working correctly.  If you log to a json file you can see the correct (untruncated) target values

**Comment by MrLuuuu** [comment] 2021-12-17 15:48
I also meet this issue, the default length of parameter to print is defined in the file "logger.py", and you can modify the 15 line code.

**Comment by till-m** [comment] 2022-08-22 11:09
Fixed in #282?

**Closed** 2022-10-27 01:50 UTC
Labels: bug
