### ISSUE TITLE
Incorrect dependencies 

### ISSUE THREAD

**Issue by alailink** [fmfn/BayesianOptimization#397] opened 2023-02-15 19:59 UTC
**Describe the bug**
After successfully solving for dependencies, bayesian-optimization is installed with dependencies. Apparently, though, not all dependencies have been installed.

Using `python==3.8.13` with `bayesian-optimization==1.4.2` results in `ImportError: cannot import name 'just_fix_windows_console' from 'colorama'`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../lib/python3.9/site-packages/bayes_opt/__init__.py", line 1, in <module>
    from .bayesian_optimization import BayesianOptimization, Events
  File "/home/.../lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py", line 5, in <module>
    from .target_space import TargetSpace
  File "/home/.../lib/python3.9/site-packages/bayes_opt/target_space.py", line 4, in <module>
    from .util import ensure_rng, NotUniqueError
  File "/home/.../lib/python3.9/site-packages/bayes_opt/util.py", line 5, in <module>
   
 from colorama import just_fix_windows_console
ImportError: cannot import name 'just_fix_windows_console' from 'colorama' (/home/.../lib/python3.9/site-packages/colorama/__init__.py)
```

**To Reproduce**
from bayes_opt import BayesianOptimization

**Expected behavior**
I expected the package to install with all required dependencies.

**Environment (please complete the following information):**
 - OS: CentOS Linux 7
 - package manager: Conda 4.13.0
 - `python` Version [e.g. 3.8.13]
 - `numpy` Version [e.g. 1.20.3]
 - `scipy` Version [e.g. 1.8.1]
 - `bayesian-optimization` Version [e.g. 1.4.2]

**Additional context**
My guess is this is a simple fix which includes colorama in the setup file.

**Comment by bwheelz36** [comment] 2023-02-16 00:58
Hi, thanks for reporting.
Actually, if you look at our [tests](https://github.com/fmfn/BayesianOptimization/blob/master/.github/workflows/run_tests.yml) you will see that building against python3.8 is one of the actions carried out by CI, and is passing. 

In addition, I built python 3.8.13 from scratch and pip installed bayesian-optimization in a fresh environment; I am unable to reproduce this issue (copied below). @till-m is is possible this is a conda issue? 

```bash
(venv) brendan@hairy-gardener:~/Documents/temp/bayes_opt_test$ python
Python 3.8.13 (default, Feb 16 2023, 11:51:52) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bayes_opt import BayesianOptimization
>>>
```

**Comment by till-m** [comment] 2023-02-16 09:27
Hi @alailink,

thanks for reporting this bug.
Could you please list the version of colorama that you have installed (presumably there is one installed, otherwise the error message would be different). Maybe colorama is installed already due to some other package?
Could you also double-check that you're actually on `bayesian-optimization 1.4.2`?

Two possible scenarios that could've led to this:
- We yanked the release (`1.4.1`) that didn't specify the appropriate colorama version from PyPI. but that change probably didn't propagate through to conda (I probably should've expected this). Maybe conda solved for `1.4.1` now because you have some other package that needs `colorama  <0.4.6`.
- I made a mistake in [the PR that updates](https://github.com/conda-forge/bayesian-optimization-feedstock/pull/25) the dependencies for conda.

@volpatto Is it possible to yank a release from conda? If yes, could you either show me or yank `1.4.1` yourself?

Sidenote: I also notice it says `python3.9` during the traceback, but you say you're using `3.8.13`. Could you double check all the versions information you listed?

**Comment by alailink** [comment] 2023-02-16 16:46
Thanks for the quick responses!

So, my working environment is `python 3.8.13` and I did a quick fix and re-installed `colorama 0.4.6` so I could begin working with this package.
Thus, in order to reproduce the error and report the bug, I used another environment with `python 3.9` (which I didn't notice) and the same error occurred. So, the error occurred in both versions of python.

You are correct, and in the "bug" versions `colorama 0.4.4` was previously installed. Both times, `bayesian-optimization 1.4.2` was installed. 

I'm not sure if it will be super helpful, but I have attached a text doc with every package installed in that environment.
[bugpackages.txt](https://github.com/fmfn/BayesianOptimization/files/10758338/bugpackages.txt)

**Comment by volpatto** [comment] 2023-02-17 04:04
Hi, @alailink.

Thanks for reporting the bug.

Unfortunately, I was unable to reproduce the issue. However, I am quite interested to track down what is causing the problem. Would you mind to do some checks in your local environment, please? I will list them below.

1. From your `base` `conda` environment, create a new env from scratch:
```bash
conda create -n bayesopt python=3.8.13
```
2. Activate the new env and install `bayesian-optimization` from `conda-forge` channel:
```bash
conda activate bayesopt
conda install -c conda-forge bayesian-optimization
```
3. Check if the installation is broken:
```bash
python -c "from bayes_opt import BayesianOptimization"
```
4. After the steps below, could you please provide the package installed in your env? (as you did in your last reply)

---------------------------------------------

In theory, what you have observed is very unlikely to occur, because the `conda` package build in `conda-forge` (you can check the [feedstock's recipe here](https://github.com/conda-forge/bayesian-optimization-feedstock/blob/main/recipe/meta.yaml#L26)) enforces the right `colorama` version (0.4.6). I can list some ways to corrupt your `bayesian-optimization` installation and you can check if you have did some of them:

1. `conda` + `pip`. What I can say? They don't get along very well sometimes. An example that is error-prone is add a `pip:` field in your `environment.yml` if you have one. 
2. Another example that can be problematic is: after the installation of `bayesian-optimization`, you installed another package afterward. Say, you do `conda install -c conda-forge bayesian-optimization` and, then, you do `conda install foo_package`. This can mess things around, but conda will try to advertise the changes with something like:
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bayesian-optimization-1.4.2|     pyhd8ed1ab_1          20 KB  conda-forge
    colorama-0.4.6             |     pyhd8ed1ab_0          25 KB  conda-forge
    joblib-1.2.0               |     pyhd8ed1ab_0         205 KB  conda-forge
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libgfortran-ng-12.2.0      |      h69a702a_19          22 KB  conda-forge
    libgfortran5-12.2.0        |      h337968e_19         1.8 MB  conda-forge
    liblapack-3.9.0            |16_linux64_openblas          13 KB  conda-forge
    libopenblas-0.3.21         |pthreads_h78a6416_3        10.1 MB  conda-forge
    numpy-1.24.2               |   py38h10c12cc_0         6.3 MB  conda-forge
    python_abi-3.8             |           2_cp38           4 KB  conda-forge
    scikit-learn-1.2.1         |   py38h1e1a916_0         7.3 MB  conda-forge
    scipy-1.9.3                |   py38h8ce737c_2        26.3 MB  conda-forge
    threadpoolctl-3.1.0        |     pyh8a188c0_0          18 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        52.1 MB
```
but for a DOWNGRADING. So yeah, it is a good thing to check when changing an `env`.
3. The same as the last one, but even more tricky: You install another package afterward but with `pip`. This has a higher risk and can mess with symlinks and deps (in your `env`) without warning you. It will just indicate, during the `pip`'s package installation procedure, that `colorama` (for instance) is being downloaded and installed.

I hope it helps to identify why you faced an error.

----------------------------------------------------

Apologies if any of the things I said above is not new to you, I just want you to check what happened and if this is an issue within `conda-forge`, action at our side (the feedstock maintainers) should be performed.

**Comment by volpatto** [comment] 2023-02-17 04:11
> @volpatto Is it possible to yank a release from conda? If yes, could you either show me or yank `1.4.1` yourself?

@till-m, I believe, yeah, it is possible. TBH, unfortunately I am not experienced with patches in `conda-forge`. I just did a quick search and found [this section in the docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages). Maybe it helps to figure it out what we have to do. I am unable to do it myself until next month, sorry.

**Comment by till-m** [comment] 2023-02-17 09:31
I think I found the problem: What was installed was `bayesian-optimization 1.4.2 pyhd8ed1ab_0` which has not specified a colorama version, which `bayesian-optimization 1.4.2 pyhd8ed1ab_1` (build number 1) has. I expected that a higher build number at the same version would replace the package on `conda-forge`, but I guess that is not the case.

To my understanding there's two ways to proceed:
1. Mark `1.4.2 build 0` as broken.
2. Try to patch `1.4.2. build 0`, making it functionally identical to `1.4.2 build 1`. This should be possible since the problem is in the metadata (`recipe.yml`).

Irrespective of which, I will submit a request to mark `1.4.1` as broken.

**Comment by alailink** [comment] 2023-02-18 17:08
@volpatto Thanks for all of the very specific help and tips. Theoretically I know how all of this works, but I've never maintained a package so some of it still feels a little mysterious. 

I re-compiled everything per your instructions on a fresh environment. Attached are all of the packages. No problems this time--possibly because conda grabbed version pyhd8ed1ab_1 instead of pyhd8ed1ab_0 (I think someone pulled pyhd8ed1ab_0 out of conda's repositories.)

[bugpackages.txt](https://github.com/fmfn/BayesianOptimization/files/10774788/bugpackages.txt)

**Comment by bwheelz36** [comment] 2023-02-19 21:38
thank you everyone!
can I close this as resolved?

**Comment by till-m** [comment] 2023-02-21 08:21
Not yet please, haven't figured out how to fix the problem with `1.4.2 build 0`.

**Comment by till-m** [comment] 2023-03-06 07:49
(still waiting for the patch PR to get merged)

**Comment by till-m** [comment] 2023-03-08 15:31
It looks like the problem is patched now (would appreciate if someone else could confirm):

## Incompatible colorama installed
1. `conda create -n bopt_test`
2. `conda activate bopt_test`
3. `conda install colorama=0.4.4`
4. `conda install -c conda-forge bayesian-optimization`
5. `python -c "from bayes_opt import BayesianOptimization`
6. (`conda remove --name bopt_test --all`)

This will install `bayesian-optimization=1.4.0`.

## No colorama installed
1. `conda create -n bopt_test`
2. `conda activate bopt_test`
3. `conda install -c conda-forge bayesian-optimization`
4. `python -c "from bayes_opt import BayesianOptimization`
5. (`conda remove --name bopt_test --all`)

This will install `bayesian-optimization=1.4.2` along with `colorama=0.4.6`.

**In either case, the code should run through without error.**

**Closed** 2023-03-20 22:31 UTC
Labels: bug, enhancement
